name: hk

permissions:
  contents: read
  packages: read
  statuses: write

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: hugoh/spoon-tools/.github/workflows/spoon-hk.yml@713fb1bcd3bec558aaf1932183d435292e16e0ba # v1.3.1
