name: hk

permissions:
  contents: read
  packages: read
  statuses: write

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - renovate/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: hugoh/spoon-tools/.github/workflows/spoon-hk.yml@e462100046f5e62dd4c8e901960867f56bf6e1a1 # v1.2.6
