name: Tag

permissions:
  contents: write
  actions: write

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: tag
  cancel-in-progress: false

jobs:
  tag:
    uses: hugoh/spoon-tools/.github/workflows/spoon-tag.yml@713fb1bcd3bec558aaf1932183d435292e16e0ba # v1.3.1
