name: Tag

permissions:
  contents: write
  actions: write

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: tag
  cancel-in-progress: false

jobs:
  tag:
    uses: hugoh/spoon-tools/.github/workflows/spoon-tag.yml@42b2a96334e101258e72f186bd58c2db00f942f2 # v1.3.0
