name: Tag

permissions:
  contents: write
  actions: write

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: tag
  cancel-in-progress: false

jobs:
  tag:
    uses: hugoh/spoon-tools/.github/workflows/spoon-tag.yml@9b0196dd06b709ae53174c5075a06c7b948c5810 # v1.2.3
