name: Tests

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: hugoh/gh-workflows/setup@ae1366a14513d42c78dd993d7fbb776fda2d4530 # v1.38.6
      - run: mise run test
