name: Tests

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  test:
    uses: hugoh/spoon-tools/.github/workflows/spoon-tests.yml@e462100046f5e62dd4c8e901960867f56bf6e1a1 # v1.2.6
